### ISSUE TITLE
How to train an transformer-based language model

### ISSUE THREAD

**Issue by wingsyuan** [marian-nmt/marian#282] opened 2019-07-18 04:45 UTC
Hi,
How can I train an transformer-based language model and use this language model to calculate the perplexity of each sentence of the test set? Can you provide some examples?

Thanks a lot!!!

**Comment by snukky** [comment] 2019-07-19 12:13
A duplicate of https://github.com/marian-nmt/marian-dev/issues/465

**Closed by snukky** 2019-07-19 12:13 UTC
Labels: faq
