### ISSUE TITLE
Compiler warnings on JADE

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian#119] opened 2017-10-13 12:07 UTC
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
cuda 9 or cuda 8 (doesn't appear to matter)
master branch

There's lots of warnings like this 
```
/usr/include/c++/4.8/bits/basic_string.h:2753:1: note: candidate 1: std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
     operator<<(basic_ostream<_CharT, _Traits>& __os,
 ^
/jmain01/home/JAD003/sxr01/kjh57-sxr01/marian-dev/src/common/config.h:128:1: note: candidate 2: OStream& marian::operator<<(OStream&, const marian::Config&) [with OStream = std::basic_stringstream<char>]
   friend OStream& operator<<(OStream& out, const Config& config) {
 ^
/jmain01/home/JAD003/sxr01/kjh57-sxr01/marian-dev/src/graph/expression_graph.h: In member function ‘void marian::ExpressionGraph::graphviz(const string&)’:
/jmain01/home/JAD003/sxr01/kjh57-sxr01/marian-dev/src/graph/expression_graph.h:243:26: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: [enabled by default]
     dot << graphviz();
                          ^
/usr/include/c++/4.8/bits/basic_string.h:2753:1: note: candidate 1: std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
     operator<<(basic_ostream<_CharT, _Traits>& __os,
 ^
/jmain01/home/JAD003/sxr01/kjh57-sxr01/marian-dev/src/common/config.h:128:1: note: candidate 2: OStream& marian::operator<<(OStream&, const marian::Config&) [with OStream = std::basic_ofstream<char>]
   friend OStream& operator<<(OStream& out, const Config& config) {
 ^
/jmain01/home/JAD003/sxr01/kjh57-sxr01/marian-dev/src/graph/expression_graph.h:243:26: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: [enabled by default]
     dot << graphviz();
                          ^
/usr/include/c++/4.8/bits/basic_string.h:2753:1: note: candidate 1: std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
     operator<<(basic_ostream<_CharT, _Traits>& __os,
 ^
/jmain01/home/JAD003/sxr01/kjh57-sxr01/marian-dev/src/common/config.h:128:1: note: candidate 2: OStream& marian::operator<<(OStream&, const marian::Config&) [with OStream = std::basic_ofstream<char>]
   friend OStream& operator<<(OStream& out, const Config& config) {
```

**Comment by emjotde** [comment] 2017-10-16 20:23
@snukky can you get access to JADE? It's probably something stupid with the old compiler. Maybe an explicite conversion to std::string would already fix that.

**Comment by emjotde** [comment] 2017-10-17 15:56
So, do we close this since GCC 5 is being installed?

**Comment by kpu** [comment] 2017-10-17 16:35
Guess we don't care about the compiler warnings or JADE.  But @fiqas was getting weird crashes with the compiled version.  So it may be worth investigating that,, if only to save from debugging for some other user with GCC 4.

**Comment by fiqas** [comment] 2017-10-17 17:16
I suspect it’s locale settings after all, but better check than be sorry.

**Comment by snukky** [comment] 2017-10-30 11:37
My comments:

* I can compile and run the current version of marian-dev on JADE with default gcc 4.8.4
* I need to download and use newer CMake
* For training I need to set LC_ALL
* All our regression tests pass
* It seems there is no boost on "small" partition, so I use "big" partition
* I can compile and run marian-dev with a gcc 4.9.4 compiled from sources as well
* I can't compile marian with gcc 5.5.0 available as a module due to nvcc errors

For ro-en example from marian/examples/training I'm getting:

* ~10k WPS with 1 GPU
* ~33-24k WPS with 4 GPUs and async SGD
* ~28-29k WPS with 4 GPUs and sync SGD

**Comment by tomekd** [comment] 2017-10-30 12:03
@snukky : do you mean ~33-34k with async?

**Comment by snukky** [comment] 2017-10-30 12:08
Yes, ~34k with asynchronous multi-GPU training.

**Comment by emjotde** [comment] 2017-11-10 21:57
Closing this. The compiler warnings are fixed in `marian-dev`. Will soon update here.

**Closed by emjotde** 2017-11-10 21:57 UTC
