### ISSUE TITLE
Support source side factors as in Nematus

### ISSUE THREAD

**Issue by oraveczcsaba** [marian-nmt/marian#14] opened 2016-10-10 09:59 UTC

**Comment by mjpost** [comment] 2017-05-17 20:41
Looking a bit into the code, it seems that source-side factors are supported, but that the input representation is different? Whereas Moses and Nematus use:

    word1|factor11|factor12 word2|factor21|factor22 ...

The code in the `common/sentence.cpp` constructor seems to expect something like

    word1 word2 ... TAB factor11 factor21 ... TAB factor12 factor22 ...

Can someone confirm this? I have tried changing Nematus factors to this format, and extending the source dictionaries to a list in the format:

    source-vocal: [dict1, dict2, dict3, ...]

but it doesn't produce good output, and I thought I'd ask here to see if anyone has it working before I dug too deep.

**Comment by emjotde** [comment] 2017-05-17 21:06
Negative. These are separate input sequences to models that have different input vocabularies but matching output vobularies. I have been using this to build multilingual ensembles for automatic post-editing. There is not 1-1 correspondence between the two input sequences.

**Comment by rihardsk** [comment] 2017-10-18 14:00
I intend to implement source side factors in Amun. @hieuhoang would this conflict with any other ongoing work?

This would basically boil down to refactoring _types.h_
```c++
// from this
typedef size_t Word;
typedef std::vector<Word> Words;
// to this
typedef size_t Factor;
typedef std::vector<Factor> Word;
typedef std::vector<Word> Words;
```

Though the problem is that the target side doesn't use factors so we'd have to either:
1) Use factors in source and target, but treat the target side as a special case where we limit it to a single factor.
2) Treat encoding and decoding differently - on the source side we would have `EncWord` that is a vector of `Factor`s, and on the target side we'd leave `Word` to mean `size_t`. This would require to duplicate `Sentence` and `Sentences` classes for source and target.

I'd probably go with the option 2) because that would mean less refactoring.

**Comment by tomekd** [comment] 2017-10-18 14:52
Maybe do easy start and then refactor.

3. Pass the factors as normal words, e.g. ``w1 f1 f2 w2 f1 f2`` etc. Then work around ``sentence.cpp`` to use correct vocab. 

I'd start with loading the model in ``{gpu,cpu}/dl4mt/model.h``. It should be easy to get the number of  
The most of work is in the ``Encoder::Embeddings`` class. Change Lookup method to handle many embeddings matrices.

**Comment by hieuhoang** [comment] 2017-10-18 16:47
no conflicts. Go for it

**Comment by rihardsk** [comment] 2017-10-19 07:57
@tomekd thanks for the idea, I think I'll do that. The work that needs to be done for 3. is almost a subset of 2.

**Comment by tomekd** [comment] 2017-10-19 12:57
@rihardsk : that's my point. To create a simple prototype firstly. Then improve to 2. or 1. It's up to you.

**Comment by hieuhoang** [comment] 2018-01-24 17:51
factors have been added right? I'll close this issue unless anyone objects

**Comment by emjotde** [comment] 2018-01-24 17:53
Objecting, only in amun

**Comment by snukky** [comment] 2021-01-11 10:49
Closing this issue. Factors have been added some time ago, and the documentation will be added with https://github.com/marian-nmt/marian-dev/pull/748.

**Closed by snukky** 2021-01-11 10:49 UTC
Labels: enhancement
