### ISSUE TITLE
Ensemble decoding fails with any of alignment flags set

### ISSUE THREAD

**Issue by rihardsk** [marian-nmt/marian#140] opened 2017-12-14 13:48 UTC
[I found an `assert(false)`](https://github.com/marian-nmt/marian/blob/9f4addbf22d9396b89184db4ac231756b0f77510/src/amun/gpu/mblas/nth_element.cu#L157) which gets triggered when running ensembles with any of the alignment options enabled:
```
return-alignment
return-soft-alignment
return-nematus-alignment
```
It was introduced by @hieuhoang in 4a58c88d3373583f15664a69b94f809a4b1e77e4

Removing the assert lets me get a translation, but I have little understanding of what the code in `NthElement::getValueByKey` should be doing.

**Comment by tomekd** [comment] 2017-12-14 14:09
Hi,

**tl;dr**: ``NthElement::getValueByKey``: get scores from a given matrix.

In ensemble configuration, we sum all the scores to one matrix and then we search for n best scores. But n-best-list shows scores separated for each model, so we need a way to get these numbers. This is what the function does.

**Comment by hieuhoang** [comment] 2017-12-14 22:27
I didn't think the function was doing it job so I explicitly added the assert(false) to case the failure. The source vector, d_breakdown, never seems to be set.

I'm not sure if and when nbest worked. If anyone has results they are confident about, we can create regression tests. In the meantime, I've created tests but I don't think they are correct

**Comment by emjotde** [comment] 2017-12-14 22:28
N-best lists used to work w/o problems in my time.

**Comment by hieuhoang** [comment] 2017-12-14 22:30
for ensemble? Do you have models & results?

**Comment by emjotde** [comment] 2017-12-14 22:32
I have a paper I used this for a lot with 8 and more models in an ensemble, doing MERT and stuff. It's been a while though. Should be identical to Marian's out put for --n-best list.

**Comment by emjotde** [comment] 2017-12-14 22:35
https://github.com/marian-nmt/marian/wiki/AmuNMT-for-Automatic-Post-Editing

Commit 3833669

@snukky. But the file server seems to be down. Can you update this?

**Comment by tomekd** [comment] 2017-12-15 12:07
So I suppose that getting n-best-list with model ensembling is unavailable now, isn't it? The function is obviously broken but easy to fix. I can fix it in this weekend.

**Comment by hieuhoang** [comment] 2017-12-15 12:14
ya, apologies. No regression tests so didn't know the functionalitty existed until I had already broken it

**Comment by tomekd** [comment] 2017-12-15 12:26
no worries :) Nobody hasn't complained about this yet. We should add some tests with a model ensemble configuration.

**Comment by hieuhoang** [comment] 2017-12-15 12:28
ya, I've added 3 tests for each of the alignments options. You should add 1 for n-best once you've fixed it

**Comment by hieuhoang** [comment] 2018-01-24 17:47
@tomekd did you fix what you had to fix? lets close this issue if there's nothing else remaining

**Comment by hieuhoang** [comment] 2018-01-25 22:43
i believe everything has been fixed. Re-open if I'm wrong

**Closed by hieuhoang** 2018-01-25 22:43 UTC
